
dubbo:
  application:
    name: provider
  registry:
    address: zookeeper://192.168.25.3:2181?backup=192.168.25.3:2182,192.168.25.3:2183
    timeout: 6000
  metadata-report:
    address: zookeeper://192.168.25.3:2181?backup=192.168.25.3:2182,192.168.25.3:2183
  protocol:
    name: dubbo
    port: 20881
  scan:
   base-packages: com.lllfff.service
server:
  port: 8001



